module.exports = {
  ERROR: "error",
  CONNECTION: "connection",
  DISCONNECT: "disconnect",
  CLIENT_JOIN_ROOM: "client-join-room",
  CLIENT_CREATE_CONVERSATION: "client-create-conversation",
  CLIENT_SEND_MESSAGE: "client-send-message",
  CLIENT_SEND_FILE: "client-send-file",
  CLIENT_GET_CONVERSATIONS: "client-get-conversations",
  CLIENT_RECALL_MESSAGE: "client-recall-message",
  CLIENT_ADD_TO_CONVERSATION: "client-add-to-conversation",
  CLIENT_RENAME_GROUP: "client-rename-group",
  CLIENT_LEAVE_CONVERSATION: "client-leave-conversation",
  CLIENT_LEAVE_ROOM_SOCKET: "client-leave-room-socket",
  SV_SEND_CONVERSATION: "server-send-conversation",
  SV_SEND_INVITATION_JOIN_ROOM: "server-send-invitation-join-room",
  SV_SEND_MESSAGE: "server-send-message",
  SV_SEND_FILE: "server-send-file",
  SV_SEND_CONVERSATIONS: "server-send-conversations",
  SV_SEND_USER_LEAVE_CONVERSATION: "server-send-user-leave-conversation",
  SV_SEND_USER: "server-send-user",
};
