module.exports = {
  ERROR: "error",
  CONNECTION: "connection",
  DISCONNECT: "disconnect",
  CLIENT_JOIN_ROOM: "client-join-room",
  CLIENT_CREATE_CONVERSATION: "client-create-conversation",
  CLIENT_SEND_MESSAGE: "client-send-message",
  CLIENT_SEND_FILE: "client-send-file",
  CLIENT_GET_CONVERSATIONS: "client-get-conversations",
  SV_SEND_CONVERSATION: "server-send-conversation",
  SV_SEND_INVITATION_JOIN_ROOM: "server-send-invitation-join-room",
  SV_SEND_MESSAGE: "server-send-message",
  SV_SEND_FILE: "server-send-file",
  SV_SEND_CONVERSATIONS: "server-send-conversations",
};
